/**
 * L6 synthesis orchestrator + report stitcher.
 *
 * Pulls all facts, clusters them, writes one section per cluster, then
 * stitches into a single Markdown file at .sheldon/reports/<runId>.md
 * (and copies to latest.md).
 *
 * The stitcher is a pure function exported as `stitchReport`; the
 * orchestrator wraps it with I/O.
 */

import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import { join } from 'node:path';
import { factStore } from './facts.ts';
import { clusterFacts, type Cluster } from './cluster.ts';
import { writeSection, writeIntro, writeOutro, type Section, type SectionFact, type RunStats } from './sections.ts';
import { getRunState } from './phase.ts';
import { events } from './events.ts';
import { getDb } from './db.ts';

const MAX_FACTS_PER_SECTION = 12;

function dot(a: Float32Array, b: Float32Array): number {
  const n = Math.min(a.length, b.length);
  let s = 0;
  for (let i = 0; i < n; i++) s += a[i]! * b[i]!;
  return s;
}

/**
 * If a cluster has more than MAX_FACTS_PER_SECTION facts, keep only the ones
 * closest to its centroid. This keeps section prompts small enough that
 * generation finishes inside Cloudflare's edge timeout.
 */
function trimToCentroid(
  factIds: number[],
  centroid: Float32Array,
  factsById: Map<number, { embedding: Float32Array }>,
): number[] {
  if (factIds.length <= MAX_FACTS_PER_SECTION) return factIds;
  const scored = factIds.map((id) => ({
    id,
    sim: dot(factsById.get(id)!.embedding, centroid),
  }));
  scored.sort((a, b) => b.sim - a.sim);
  return scored.slice(0, MAX_FACTS_PER_SECTION).map((s) => s.id);
}

export type SectionInReport = {
  label: string;
  body: string;
  factIds: number[]; // global fact ids (DB ids) in order matching local 1..N positions
};

export type FactById = Map<number, { sourceUrl: string; sourceTitle: string | null }>;

export type StitchInput = {
  task: string;
  intro: string;
  sections: SectionInReport[];
  outro: string;
  factsById: FactById;
  runStats: RunStats;
  generatedAt: number;
};

export type StitchOutput = {
  markdown: string;
  globalCitationOrder: string[]; // urls in first-appearance order; 1-indexed via array position
};

const REPORTS_DIR = '.sheldon/reports';

/**
 * Pure function: take section bodies with local [N] citations, renumber to
 * globally unique [M] (collapsing duplicate URLs), and render the full report.
 */
export function stitchReport(input: StitchInput): StitchOutput {
  const urlToGlobal = new Map<string, number>();
  const globalOrder: string[] = []; // url at index M-1
  const titleByUrl = new Map<string, string>();

  function globalFor(url: string, title: string | null): number {
    let g = urlToGlobal.get(url);
    if (g === undefined) {
      globalOrder.push(url);
      g = globalOrder.length;
      urlToGlobal.set(url, g);
      titleByUrl.set(url, title ?? '');
    }
    return g;
  }

  function rewriteSection(section: SectionInReport): string {
    return section.body.replace(/\[(\d+)\]/g, (full, n) => {
      const localId = Number(n);
      const factId = section.factIds[localId - 1];
      if (factId === undefined) return ''; // no mapping; drop
      const fact = input.factsById.get(factId);
      if (!fact) return '';
      const g = globalFor(fact.sourceUrl, fact.sourceTitle);
      return `[${g}]`;
    });
  }

  const renderedSections = input.sections.map((s) => ({
    label: s.label,
    body: rewriteSection(s),
  }));

  const date = new Date(input.generatedAt).toISOString().slice(0, 10);
  const elapsedMin = (input.runStats.elapsedMs / 60000).toFixed(1);

  const lines: string[] = [];
  lines.push(`# ${input.task}`);
  lines.push('');
  lines.push(
    `_Generated by Sheldon on ${date}. Researched for ${elapsedMin} min · ${input.runStats.iterations} iterations · ${input.runStats.factCount} facts._`,
  );
  lines.push('');
  if (input.intro.trim()) {
    lines.push(input.intro.trim());
    lines.push('');
  }

  for (const s of renderedSections) {
    if (!s.body.trim()) continue;
    lines.push(`## ${s.label}`);
    lines.push('');
    lines.push(s.body.trim());
    lines.push('');
  }

  if (input.outro.trim()) {
    lines.push('## Conclusion');
    lines.push('');
    lines.push(input.outro.trim());
    lines.push('');
  }

  if (globalOrder.length > 0) {
    lines.push('## Sources');
    lines.push('');
    for (let i = 0; i < globalOrder.length; i++) {
      const url = globalOrder[i]!;
      const title = titleByUrl.get(url) ?? '';
      const display = title ? `${title} — ${url}` : url;
      lines.push(`[${i + 1}] ${display}`);
    }
    lines.push('');
  }

  return { markdown: lines.join('\n'), globalCitationOrder: globalOrder };
}

export type SynthesizeResult = {
  reportPath: string;
  latestPath: string;
  sectionCount: number;
  factCount: number;
  bytes: number;
};

export async function synthesize(): Promise<SynthesizeResult | null> {
  const runState = getRunState();
  if (!runState) {
    throw new Error('synthesize: no run_state row — start a run first');
  }

  const facts = factStore.listAllWithEmbeddings();
  if (facts.length === 0) {
    return null;
  }

  // Cluster.
  const clusters = await clusterFacts(
    facts.map((f) => ({
      id: f.id,
      embedding: f.embedding,
      topicTag: f.topicTag,
      claim: f.claim,
    })),
  );

  // If clustering returned nothing (very small store), build a single
  // implicit cluster of all facts so the user still gets a report.
  let workingClusters: Cluster[] = clusters;
  if (workingClusters.length === 0 && facts.length >= 1) {
    workingClusters = [
      {
        label: 'findings',
        factIds: facts.map((f) => f.id),
        centroid: new Float32Array(facts[0]!.embedding),
      },
    ];
  }

  // Per-cluster: write section.
  const factById: Map<number, (typeof facts)[number]> = new Map();
  for (const f of facts) factById.set(f.id, f);

  // Build a centroid lookup for trimming.
  const factsByIdForCentroid = new Map<number, { embedding: Float32Array }>();
  for (const f of facts) factsByIdForCentroid.set(f.id, { embedding: f.embedding });

  const sectionsForReport: SectionInReport[] = [];
  for (const cluster of workingClusters) {
    const trimmedIds = trimToCentroid(cluster.factIds, cluster.centroid, factsByIdForCentroid);
    const factsForSection: SectionFact[] = [];
    trimmedIds.forEach((fid, idx) => {
      const f = factById.get(fid)!;
      factsForSection.push({
        localId: idx + 1,
        claim: f.claim,
        sourceUrl: f.sourceUrl,
        ...(f.sourceTitle ? { sourceTitle: f.sourceTitle } : {}),
        confidence: f.confidence,
      });
    });
    const section = await writeSection(
      { label: cluster.label, facts: factsForSection },
      { originalTask: runState.task },
    );
    if (!section.body.trim()) continue;
    sectionsForReport.push({
      label: section.label,
      body: section.body,
      factIds: trimmedIds, // 1-indexed via position; matches prompt's localIds
    });
  }

  if (sectionsForReport.length === 0) {
    return null;
  }

  // Intro / outro see only labels.
  const labels = sectionsForReport.map((s) => s.label);
  // Iterations = frontier rows that reached a terminal state (done or skipped).
  // This is durable across crash + resume, unlike the in-memory loop counter.
  const iterationCount = (
    getDb()
      .query(
        `SELECT COUNT(*) AS n FROM frontier WHERE status IN ('done','skipped')`,
      )
      .get() as { n: number }
  ).n;

  const runStats: RunStats = {
    iterations: iterationCount,
    factCount: facts.length,
    elapsedMs: Date.now() - runState.startedAt,
  };
  const intro = await writeIntro(runState.task, labels, runStats);
  const outro = await writeOutro(runState.task, labels, runStats);

  // Build factsById view for stitcher.
  const factsByIdForStitch: FactById = new Map();
  for (const f of facts) {
    factsByIdForStitch.set(f.id, { sourceUrl: f.sourceUrl, sourceTitle: f.sourceTitle });
  }

  const generatedAt = Date.now();
  const { markdown } = stitchReport({
    task: runState.task,
    intro,
    sections: sectionsForReport,
    outro,
    factsById: factsByIdForStitch,
    runStats,
    generatedAt,
  });

  // Write to disk.
  await mkdir(REPORTS_DIR, { recursive: true });
  const runId = String(runState.startedAt);
  let reportPath = join(REPORTS_DIR, `${runId}.md`);
  // If the run-id file already exists (re-synthesizing), suffix with -v2, -v3...
  let v = 2;
  while (await pathExists(reportPath)) {
    reportPath = join(REPORTS_DIR, `${runId}-v${v}.md`);
    v++;
  }
  const latestPath = join(REPORTS_DIR, 'latest.md');
  await writeFile(reportPath, markdown, 'utf8');
  await copyFile(reportPath, latestPath);

  await events.emit({
    kind: 'report.written',
    layer: 'L6',
    payload: {
      path: reportPath,
      sectionCount: sectionsForReport.length,
      factCount: facts.length,
      bytes: Buffer.byteLength(markdown, 'utf8'),
    },
  });

  return {
    reportPath,
    latestPath,
    sectionCount: sectionsForReport.length,
    factCount: facts.length,
    bytes: Buffer.byteLength(markdown, 'utf8'),
  };
}

async function pathExists(p: string): Promise<boolean> {
  try {
    return await Bun.file(p).exists();
  } catch {
    return false;
  }
}
